sudo: required
services:
  - docker

before_install:
  - docker build -t cedrikaagaard/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cedrikaagaard/react-test npm test

after_success:
  - docker build -t cedrikaagaard/multi-client ./client
  - docker build -t cedrikaagaard/multi-nginx ./nginx
  - docker build -t cedrikaagaard/multi-server ./server
  - docker build -t cedrikaagaard/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cedrikaagaard/multi-client
  - docker push cedrikaagaard/multi-nginx
  - docker push cedrikaagaard/multi-server
  - docker push cedrikaagaard/multi-worker
  # Take those images and push them to docker hub

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-north-1-872583650794
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY